language: R
sudo: false
cache: packages
dist: trusty

before_install:
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

env:
  global:
  - R_CHECK_ARGS="--timings"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"

notifications:
  email: false
  
r_packages:
  - forcats
  - survival
  - dplyr
  - knitr
  - survminer
